/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "debridav"

if (file("../yenc_kotlin_wrapper").exists()) {
    includeBuild("../yenc_kotlin_wrapper") {
        dependencySubstitution {
            substitute(module("com.github.skjaere:rapidyenc-kotlin-wrapper")).using(project(":"))
        }
    }
}

if (file("../ktor-nntp-client").exists()) {
    includeBuild("../ktor-nntp-client") {
        dependencySubstitution {
            substitute(module("com.github.skjaere:ktor-nntp-client")).using(project(":"))
        }
    }
}

if (file("../nzb-streamer").exists()) {
    includeBuild("../nzb-streamer") {
        dependencySubstitution {
            substitute(module("com.github.skjaere:nzb-streamer")).using(project(":"))
        }
    }
}

if (file("../mock-nntp-server/mock-nntp-server").exists()) {
    includeBuild("../mock-nntp-server/mock-nntp-server") {
        dependencySubstitution {
            substitute(module("io.skjaere.mocknntp:mock-nntp-server")).using(project(":"))
        }
    }
}
