{
 "title": "DebriDav: Platform",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "DebriDav: platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Streams",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "debridav_input_stream_bitrate", "legendFormat": "{{provider}}::{{file}}" },
    { "expr": "nzb_streams_bitrate", "legendFormat": "NNTP::{{name}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "Cpu usage" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "Memory usage" }
   ]
  },
  {
   "title": "Logged errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(logback_events_total{level=\"error\"}[1m])",
     "legendFormat": "logged errors ( 1m )"
    }
   ]
  },
  {
   "title": "Library",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Library Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      { "expr": "debridav_library_size", "legendFormat": "Files: {{source}}" }
     ]
    },
    {
     "title": "Easynews",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debridav_library_metrics{provider=\"EASYNEWS\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Premiumize",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debridav_library_metrics{provider=\"PREMIUMIZE\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Real-Debrid",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debridav_library_metrics{provider=\"REAL_DEBRID\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Torbox",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debridav_library_metrics{provider=\"TORBOX\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Incoming traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"debridav\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    { "expr": "hikaricp_connections", "legendFormat": "Connection pool size" },
    { "expr": "hikaricp_connections_active", "legendFormat": "Active connections" },
    { "expr": "hikaricp_connections_pending", "legendFormat": "Pending connections" }
   ]
  },
  {
   "title": "Large objects size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pg_largeobjects_sum", "legendFormat": "Size" }
   ]
  },
  { "title": "Rate limiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Rate limiters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "resilience4j_ratelimiter_available_permissions",
     "legendFormat": "Available permissions: {{name}}"
    },
    {
     "expr": "resilience4j_ratelimiter_waiting_threads",
     "legendFormat": "Waiting threads: {{name}}"
    }
   ]
  },
  { "title": "Rclone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Rclone errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    { "expr": "rate(rclone_errors_total[5m])", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "Rclone transfer rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rclone_bytes_transferred_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}