-- Merged from V11–V21

CREATE TABLE nzb_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    files JSONB NOT NULL,
    streamable_files JSONB NOT NULL DEFAULT '[]'::jsonb,
    archive_type VARCHAR(30) NOT NULL DEFAULT 'RAW',
    last_verified TIMESTAMP WITH TIME ZONE,
    health_check_enqueued_at TIMESTAMP WITH TIME ZONE,
    category VARCHAR(255),
    name VARCHAR(255),
    download_id VARCHAR(255)
);

DROP TABLE IF EXISTS debrid_usenet_contents;

CREATE TABLE nzb_contents (
    id                      BIGINT NOT NULL,
    debrid_links            JSONB,
    mime_type               VARCHAR(255),
    modified                BIGINT,
    original_path           VARCHAR(255),
    size                    BIGINT,
    nzb_document_id         BIGINT,
    CONSTRAINT nzb_contents_pkey PRIMARY KEY (id),
    CONSTRAINT fk_nzb_contents_document FOREIGN KEY (nzb_document_id) REFERENCES nzb_document (id) ON DELETE NO ACTION
);

ALTER TABLE usenet_download ADD COLUMN nzb_document_id BIGINT;
ALTER TABLE usenet_download ADD CONSTRAINT fk_usenet_download_nzb_document
    FOREIGN KEY (nzb_document_id) REFERENCES nzb_document(id);
